version: "3.7"
services:
  database:
    image: postgres:11.3-alpine
    container_name: rallyai-stocks-historical-data-store
    volumes:
      - "./database/:/docker-entrypoint-initdb.d"
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3
  cache:
    image: redis:5.0.6-alpine
    container_name: rallyay-redis-cache
    ports:
      - "6379:6379"
    restart: always
    depends_on:
      - database
  api:
    build: ./api
    container_name: rallyay-graphql-api
    env_file: .env
    ports:
      - "3000:3000"
    restart: always
  etl_pipeline:
    build: ./pipeline
    container_name: rallyay-data-pipeline-notebook
    volumes:
      - "./pipeline:/rallyai/spark-etl-pipeline"
    env_file: .env
    ports:
      - "8888:8888"
