version: "3.7"
services:
  database:
    image: postgres:11.3-alpine
    container_name: rallyai-stocks-historical-data-store
    volumes:
      - "./database/:/docker-entrypoint-initdb.d"
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3
