version: "3.7"
services:
  database:
    image: postgres:11.3-alpine
    container_name: rallyai-stocks-historical-data-store
    volumes:
      - "./database/:/docker-entrypoint-initdb.d"
    restart: always
    env_file: .env
    environment:
      CSV_FILE_PATH: ${CSV_FILE_PATH}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_ADDRESS: ${DB_ADDRESS}
      DB_TABLE: ${DB_TABLE}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3
  spark_notebook:
    build: ./pipeline
    container_name: rallyay-data-pipeline-notebook
    volumes:
      - "./pipeline:/rallyai/spark-etl-pipeline"
    env_file: .env
    ports:
      - "8888:8888"
